global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'go-backend-external'
    metrics_path: '/metrics'
    scheme: https
    
    static_configs:
      - targets: ['mytonprovider.org:443']

    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/mtpo_bearer_token

  - job_name: 'mtso-backend'
    metrics_path: '/metrics'
    scheme: https
    
    static_configs:
      - targets: ['mytonstorage.org:443']

    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/mtso_bearer_token

  - job_name: 'gateway-backend'
    metrics_path: '/gateway/metrics'
    scheme: https
    
    static_configs:
      - targets: ['mytonstorage.org:443']

    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/gateway_bearer_token